# Generated by Django 3.2.12 on 2022-03-29 22:14

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='员工ID')),
                ('name', models.CharField(max_length=100, verbose_name='员工姓名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '人员管理',
                'verbose_name_plural': '人员管理',
            },
        ),
        migrations.CreateModel(
            name='ItemInformationModel',
            fields=[
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('item_number', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='项目编号')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('project_status', models.CharField(choices=[('sxqh', '上线切换'), ('xmqd', '项目启动'), ('xmzx', '项目执行'), ('xmqd', '项目启动'), ('xqdy', '需求调研'), ('syx', '试运行'), ('dnbys', '待内部验收')], default='xmqd', max_length=10, verbose_name='项目状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
            },
        ),
        migrations.CreateModel(
            name='SystemEnvironmentDocumentationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file_name', models.CharField(max_length=100, verbose_name='文档名称')),
                ('appendix', models.FileField(upload_to='sed/a/%Y/%m', verbose_name='附件')),
                ('remark', models.TextField(verbose_name='备注')),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.iteminformationmodel', verbose_name='项目编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '系统环境文档',
                'verbose_name_plural': '系统环境文档',
            },
        ),
        migrations.CreateModel(
            name='SoftwareInstallationPackageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('software_name', models.CharField(max_length=100, verbose_name='软件名称')),
                ('installation_package', models.FileField(upload_to='sip/ip/%Y/%m', verbose_name='安装包')),
                ('deployment_documentation', models.FileField(upload_to='sip/dd/%Y/%m', verbose_name='部署文档')),
                ('remark', models.TextField(verbose_name='备注')),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.iteminformationmodel', verbose_name='项目编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '软件安装包',
                'verbose_name_plural': '软件安装包',
            },
        ),
        migrations.CreateModel(
            name='RiskManagementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('visit_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='访问链接')),
                ('e_edition', models.FileField(upload_to='rm/ee/%Y/%m', verbose_name='问题清单电子版')),
                ('signed_version', models.FileField(upload_to='rm/sv/%Y/%m', verbose_name='纸质签字版')),
                ('email_screenshot', models.ImageField(upload_to='rm/es/%Y/%m', verbose_name='邮件反馈确认截图')),
                ('remark', models.TextField(verbose_name='备注')),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.iteminformationmodel', verbose_name='项目编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '风险管理',
                'verbose_name_plural': '风险管理',
            },
        ),
        migrations.CreateModel(
            name='RequestingResearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('requirements_file_name', models.CharField(max_length=100, verbose_name='需求文件名称')),
                ('requirements_document', models.FileField(upload_to='rr/rd/%Y/%m', verbose_name='需求文件')),
                ('business_carding', models.FileField(upload_to='rr/bc/%Y/%m', verbose_name='业务梳理')),
                ('file_class', models.CharField(choices=[('xqqr', '需求确认书'), ('ltfa', '蓝图方案'), ('xqbgjl', '需求变更记录')], default='xqqr', max_length=10, verbose_name='文件类别')),
                ('electronic_file', models.FileField(upload_to='rr/el/%Y/%m', verbose_name='电子版文件')),
                ('paper_signature', models.FileField(upload_to='rr/ps/%Y/%m', verbose_name='纸质签字版')),
                ('email_screenshot', models.ImageField(upload_to='rr/es/%Y/%m', verbose_name='邮件反馈确认截图')),
                ('remark', models.TextField(verbose_name='备注')),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.iteminformationmodel', verbose_name='项目编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '需求调研',
                'verbose_name_plural': '需求调研',
            },
        ),
        migrations.CreateModel(
            name='ReportDevelopmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('requirement_name', models.CharField(max_length=100, verbose_name='需求名称')),
                ('screenshot_page', models.ImageField(upload_to='rd/sp/%Y/%m', verbose_name='页面截图')),
                ('export_template', models.FileField(upload_to='rd/et/%Y/%m', verbose_name='导出内置数据集模板')),
                ('material', models.FileField(upload_to='rd/m/%Y/%m', verbose_name='素材')),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.iteminformationmodel', verbose_name='项目编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '报表开发',
                'verbose_name_plural': '报表开发',
            },
        ),
        migrations.CreateModel(
            name='ProjectSummaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_summary_attachment', models.FileField(upload_to='ps/pas/%Y/%m', verbose_name='项目总结附件')),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.iteminformationmodel', verbose_name='项目编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '项目总结',
                'verbose_name_plural': '项目总结',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatusModel',
            fields=[
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='状态ID')),
                ('name', models.CharField(max_length=100, verbose_name='状态名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '项目状态',
                'verbose_name_plural': '项目状态',
            },
        ),
        migrations.CreateModel(
            name='ProjectStartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_initiation_Materials', models.FileField(blank=True, max_length=255, null=True, upload_to='psm/pi/%Y/%m', verbose_name='项目启动材料')),
                ('customer_office_address', models.CharField(default='上海市静安市大融城江程资产大厦', max_length=200, verbose_name='客户办公地址')),
                ('working_hours', models.CharField(default='9:00~18:00', max_length=100, verbose_name='办公时间')),
                ('project_communication_plan', models.FileField(max_length=255, upload_to='psm/pc/%Y/%m', verbose_name='项目沟通方案')),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.iteminformationmodel', verbose_name='项目编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '项目启动',
                'verbose_name_plural': '项目启动',
            },
        ),
        migrations.CreateModel(
            name='ProjectRoleModel',
            fields=[
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='角色ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '项目角色',
                'verbose_name_plural': '项目角色',
            },
        ),
        migrations.CreateModel(
            name='ProjectPlanDocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_plan_version', models.CharField(max_length=100, verbose_name='项目计划版本')),
                ('project_plan_electronic_version', models.FileField(upload_to='ppd/ppev/%Y/%m', verbose_name='项目计划电子版')),
                ('requirement_name', models.CharField(max_length=100, verbose_name='需求名称')),
                ('description_of_Requirement', models.TextField(verbose_name='需求描述')),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.iteminformationmodel', verbose_name='项目编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '项目计划文件',
                'verbose_name_plural': '项目计划文件',
            },
        ),
        migrations.CreateModel(
            name='ProjectDayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_total_day', models.IntegerField(default='0', verbose_name='项目总人天')),
                ('employee_day', models.IntegerField(default='0', verbose_name='人员投入人天')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.employeemodel', verbose_name='员工姓名')),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.iteminformationmodel', verbose_name='项目编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '项目人天',
                'verbose_name_plural': '项目人天',
            },
        ),
        migrations.CreateModel(
            name='FileClassModel',
            fields=[
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='文件类别id')),
                ('name', models.CharField(max_length=100, verbose_name='文件类别名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '文件类别',
                'verbose_name_plural': '文件类别',
            },
        ),
        migrations.CreateModel(
            name='ExternalStakeholdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('department', models.CharField(max_length=100, verbose_name='部门')),
                ('job', models.CharField(max_length=20, verbose_name='职位')),
                ('name', models.CharField(max_length=25, verbose_name='姓名')),
                ('project_role', models.CharField(max_length=15, verbose_name='项目角色')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('remark', models.TextField(verbose_name='备注')),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.iteminformationmodel', verbose_name='项目编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '外部干系人',
                'verbose_name_plural': '外部干系人',
            },
        ),
        migrations.CreateModel(
            name='EmployeeManagementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.SmallIntegerField(choices=[(1, '项目经理'), (2, '项目开发工程师')], default=1, verbose_name='项目角色')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_name', to='projects.employeemodel', verbose_name='员工姓名')),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iteminfo_employee', to='projects.iteminformationmodel', verbose_name='项目编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '项目人员管理',
                'verbose_name_plural': '项目人员管理',
            },
        ),
        migrations.CreateModel(
            name='DataDevelopmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('data_development_script', models.FileField(upload_to='dd/dds/%Y/%m', verbose_name='数据开发脚本程序')),
                ('development_documentation', models.FileField(upload_to='dd/dd/%Y/%m', verbose_name='开发文档')),
                ('remark', models.TextField(verbose_name='备注')),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.iteminformationmodel', verbose_name='项目编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '数据开发',
                'verbose_name_plural': '数据开发',
            },
        ),
        migrations.CreateModel(
            name='CommunicationManagementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='日期时间')),
                ('appendix', models.FileField(upload_to='cm/a/%Y/%m', verbose_name='附件')),
                ('remark', models.TextField(verbose_name='备注')),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.iteminformationmodel', verbose_name='项目编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '沟通管理',
                'verbose_name_plural': '沟通管理',
            },
        ),
    ]
